import {
  EntityProperty,
  EntityCanvasModel,
  RelationCanvasModel,
} from './interface';
export const mockEntityData: EntityCanvasModel[] = [
  {
    entityId: 'groups',
    name: 'groups',
    entityType: 'FACT',
    width: 170,
    height: 200,
    properties: [
      {
        propertyId: 'groupsTableProperties1',
        name: 'id',
        propertyType: 'int',
        isPK: true,
      },
      {
        propertyId: 'groupsTableProperties2',
        name: 'name',
        propertyType: 'varchar',
        isPK: false,
      },
      {
        propertyId: 'groupsTableProperties3',
        name: 'active',
        propertyType: 'boolean',
        isPK: false,
      },
      {
        propertyId: 'groupsTableProperties4',
        name: 'paid_through',
        propertyType: 'date',
        isPK: false,
      },
      {
        propertyId: 'groupsTableProperties5',
        name: 'created_utc',
        propertyType: 'datetime',
        isPK: false,
      },
    ],
  },
  {
    entityId: 'payment_types',
    name: 'payment_types',
    entityType: 'FACT',
    width: 170,
    height: 200,
    properties: [
      {
        propertyId: 'payment_typesTableProperties6',
        name: 'id',
        propertyType: 'int',
        isPK: true,
      },
      {
        propertyId: 'payment_typesTableProperties7',
        name: 'group_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'payment_typesTableProperties8',
        name: 'stripe_token',
        propertyType: 'varchar',
        isPK: false,
      },
      {
        propertyId: 'payment_typesTableProperties9',
        name: 'created_utc',
        propertyType: 'datetime',
        isPK: false,
      },
    ],
  },
  {
    entityId: 'payments',
    name: 'payments',
    entityType: 'FACT',
    width: 170,
    height: 200,
    properties: [
      {
        propertyId: 'paymentsTableProperties10',
        name: 'id',
        propertyType: 'int',
        isPK: true,
      },
      {
        propertyId: 'paymentsTableProperties11',
        name: 'payment_type_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'paymentsTableProperties12',
        name: 'amount',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'paymentsTableProperties13',
        name: 'created_utc',
        propertyType: 'datetime',
        isPK: false,
      },
    ],
  },
  {
    entityId: 'roles',
    name: 'roles',
    entityType: 'FACT',
    width: 170,
    height: 200,
    properties: [
      {
        propertyId: 'rolesTableProperties14',
        name: 'id',
        propertyType: 'int',
        isPK: true,
      },
      {
        propertyId: 'rolesTableProperties15',
        name: 'name',
        propertyType: 'varchar',
        isPK: false,
      },
    ],
  },
  {
    entityId: 'users',
    name: 'users',
    entityType: 'FACT',
    width: 170,
    height: 200,
    properties: [
      {
        propertyId: 'usersTableProperties16',
        name: 'id',
        propertyType: 'int',
        isPK: true,
      },
      {
        propertyId: 'usersTableProperties17',
        name: 'role_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'usersTableProperties18',
        name: 'group_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'usersTableProperties19',
        name: 'email',
        propertyType: 'varchar',
        isPK: false,
      },
      {
        propertyId: 'usersTableProperties20',
        name: 'display_name',
        propertyType: 'varchar',
        isPK: false,
      },
      {
        propertyId: 'usersTableProperties21',
        name: 'password',
        propertyType: 'varchar',
        isPK: false,
      },
      {
        propertyId: 'usersTableProperties22',
        name: 'active',
        propertyType: 'boolean',
        isPK: false,
      },
      {
        propertyId: 'usersTableProperties23',
        name: 'created_utc',
        propertyType: 'datetime',
        isPK: false,
      },
    ],
  },
  {
    entityId: 'transactions',
    name: 'transactions',
    entityType: 'FACT',
    width: 170,
    height: 200,
    properties: [
      {
        propertyId: 'transactionsTableProperties24',
        name: 'id',
        propertyType: 'int',
        isPK: true,
      },
      {
        propertyId: 'transactionsTableProperties25',
        name: 'user_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'transactionsTableProperties26',
        name: 'amount',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'transactionsTableProperties27',
        name: 'created_utc',
        propertyType: 'datetime',
        isPK: false,
      },
    ],
  },
  {
    entityId: 'tables',
    name: 'tables',
    entityType: 'FACT',
    width: 170,
    height: 200,
    properties: [
      {
        propertyId: 'tablesTableProperties28',
        name: 'id',
        propertyType: 'int',
        isPK: true,
      },
      {
        propertyId: 'tablesTableProperties29',
        name: 'group_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'tablesTableProperties30',
        name: 'name',
        propertyType: 'varchar',
        isPK: false,
      },
      {
        propertyId: 'tablesTableProperties31',
        name: 'seats',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'tablesTableProperties32',
        name: 'created_utc',
        propertyType: 'datetime',
        isPK: false,
      },
    ],
  },
  {
    entityId: 'players',
    name: 'players',
    entityType: 'FACT',
    width: 170,
    height: 200,
    properties: [
      {
        propertyId: 'playersTableProperties33',
        name: 'id',
        propertyType: 'int',
        isPK: true,
      },
      {
        propertyId: 'playersTableProperties34',
        name: 'user_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'playersTableProperties35',
        name: 'table_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'playersTableProperties36',
        name: 'stack',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'playersTableProperties37',
        name: 'sitting_out',
        propertyType: 'boolean',
        isPK: false,
      },
      {
        propertyId: 'playersTableProperties38',
        name: 'seat',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'playersTableProperties39',
        name: 'created_utc',
        propertyType: 'datetime',
        isPK: false,
      },
    ],
  },
  {
    entityId: 'players_active',
    name: 'players_active',
    entityType: 'FACT',
    width: 170,
    height: 200,
    properties: [
      {
        propertyId: 'players_activeTableProperties40',
        name: 'id',
        propertyType: 'int',
        isPK: true,
      },
      {
        propertyId: 'players_activeTableProperties41',
        name: 'user_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'players_activeTableProperties42',
        name: 'player_id',
        propertyType: 'int',
        isPK: false,
      },
    ],
  },
  {
    entityId: 'hands',
    name: 'hands',
    entityType: 'FACT',
    width: 170,
    height: 200,
    properties: [
      {
        propertyId: 'handsTableProperties43',
        name: 'id',
        propertyType: 'int',
        isPK: true,
      },
      {
        propertyId: 'handsTableProperties44',
        name: 'table_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'handsTableProperties45',
        name: 'dealer_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'handsTableProperties46',
        name: 'next_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'handsTableProperties47',
        name: 'rounds',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'handsTableProperties48',
        name: 'state',
        propertyType: 'states',
        isPK: false,
      },
      {
        propertyId: 'handsTableProperties49',
        name: 'created_utc',
        propertyType: 'datetime',
        isPK: false,
      },
    ],
  },
  {
    entityId: 'hands_active',
    name: 'hands_active',
    entityType: 'FACT',
    width: 170,
    height: 200,
    properties: [
      {
        propertyId: 'hands_activeTableProperties50',
        name: 'id',
        propertyType: 'int',
        isPK: true,
      },
      {
        propertyId: 'hands_activeTableProperties51',
        name: 'table_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'hands_activeTableProperties52',
        name: 'hand_id',
        propertyType: 'int',
        isPK: false,
      },
    ],
  },
  {
    entityId: 'pots',
    name: 'pots',
    entityType: 'FACT',
    width: 170,
    height: 200,
    properties: [
      {
        propertyId: 'potsTableProperties53',
        name: 'id',
        propertyType: 'int',
        isPK: true,
      },
      {
        propertyId: 'potsTableProperties54',
        name: 'hand_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'potsTableProperties55',
        name: 'amount',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'potsTableProperties56',
        name: 'created_utc',
        propertyType: 'datetime',
        isPK: false,
      },
    ],
  },
  {
    entityId: 'betting_rounds',
    name: 'betting_rounds',
    entityType: 'FACT',
    width: 170,
    height: 200,
    properties: [
      {
        propertyId: 'betting_roundsTableProperties57',
        name: 'id',
        propertyType: 'int',
        isPK: true,
      },
      {
        propertyId: 'betting_roundsTableProperties58',
        name: 'hand_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'betting_roundsTableProperties59',
        name: 'round_num',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'betting_roundsTableProperties60',
        name: 'name',
        propertyType: 'varchar',
        isPK: false,
      },
      {
        propertyId: 'betting_roundsTableProperties61',
        name: 'bet',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'betting_roundsTableProperties62',
        name: 'bettor',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'betting_roundsTableProperties63',
        name: 'state',
        propertyType: 'states',
        isPK: false,
      },
      {
        propertyId: 'betting_roundsTableProperties64',
        name: 'created_utc',
        propertyType: 'datetime',
        isPK: false,
      },
    ],
  },
  {
    entityId: 'betting_rounds_active',
    name: 'betting_rounds_active',
    entityType: 'FACT',
    width: 170,
    height: 200,
    properties: [
      {
        propertyId: 'betting_rounds_activeTableProperties65',
        name: 'id',
        propertyType: 'int',
        isPK: true,
      },
      {
        propertyId: 'betting_rounds_activeTableProperties66',
        name: 'betting_round_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'betting_rounds_activeTableProperties67',
        name: 'hand_id',
        propertyType: 'int',
        isPK: false,
      },
    ],
  },
  {
    entityId: 'bets',
    name: 'bets',
    entityType: 'FACT',
    width: 170,
    height: 200,
    properties: [
      {
        propertyId: 'betsTableProperties68',
        name: 'id',
        propertyType: 'int',
        isPK: true,
      },
      {
        propertyId: 'betsTableProperties69',
        name: 'player_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'betsTableProperties70',
        name: 'betting_round_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'betsTableProperties71',
        name: 'amount',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'betsTableProperties72',
        name: 'created_utc',
        propertyType: 'datetime',
        isPK: false,
      },
    ],
  },
  {
    entityId: 'holdings',
    name: 'holdings',
    entityType: 'FACT',
    width: 170,
    height: 200,
    properties: [
      {
        propertyId: 'holdingsTableProperties73',
        name: 'id',
        propertyType: 'int',
        isPK: true,
      },
      {
        propertyId: 'holdingsTableProperties74',
        name: 'player_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'holdingsTableProperties75',
        name: 'hand_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'holdingsTableProperties76',
        name: 'is_board',
        propertyType: 'boolean',
        isPK: false,
      },
      {
        propertyId: 'holdingsTableProperties77',
        name: 'active',
        propertyType: 'boolean',
        isPK: false,
      },
      {
        propertyId: 'holdingsTableProperties78',
        name: 'created_utc',
        propertyType: 'datetime',
        isPK: false,
      },
    ],
  },
  {
    entityId: 'cards',
    name: 'cards',
    entityType: 'FACT',
    width: 170,
    height: 200,
    properties: [
      {
        propertyId: 'cardsTableProperties79',
        name: 'id',
        propertyType: 'int',
        isPK: true,
      },
      {
        propertyId: 'cardsTableProperties80',
        name: 'code',
        propertyType: 'int',
        isPK: false,
      },
    ],
  },
  {
    entityId: 'holdings_to_cards',
    name: 'holdings_to_cards',
    entityType: 'FACT',
    width: 170,
    height: 200,
    properties: [
      {
        propertyId: 'holdings_to_cardsTableProperties81',
        name: 'holdings_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'holdings_to_cardsTableProperties82',
        name: 'cards_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'holdings_to_cardsTableProperties83',
        name: 'exposed',
        propertyType: 'boolean',
        isPK: false,
      },
    ],
  },
  {
    entityId: 'actions',
    name: 'actions',
    entityType: 'FACT',
    width: 170,
    height: 200,
    properties: [
      {
        propertyId: 'actionsTableProperties84',
        name: 'id',
        propertyType: 'int',
        isPK: true,
      },
      {
        propertyId: 'actionsTableProperties85',
        name: 'holding_id',
        propertyType: 'int',
        isPK: false,
      },
      {
        propertyId: 'actionsTableProperties86',
        name: 'type',
        propertyType: 'action_types',
        isPK: false,
      },
      {
        propertyId: 'actionsTableProperties87',
        name: 'created_utc',
        propertyType: 'datetime',
        isPK: false,
      },
    ],
  },
];

export const mockRelationData: RelationCanvasModel[] = [
  {
    relationId: 'public1',
    sourceEntityId: 'groups',
    targetEntityId: 'payment_types',
    label: '1 : N',
  },
  {
    relationId: 'public2',
    sourceEntityId: 'payment_types',
    targetEntityId: 'payments',
    label: '1 : N',
  },
  {
    relationId: 'public3',
    sourceEntityId: 'roles',
    targetEntityId: 'users',
    label: '1 : N',
  },
  {
    relationId: 'public4',
    sourceEntityId: 'groups',
    targetEntityId: 'users',
    label: '1 : N',
  },
  {
    relationId: 'public5',
    sourceEntityId: 'users',
    targetEntityId: 'transactions',
    label: '1 : N',
  },
  {
    relationId: 'public6',
    sourceEntityId: 'groups',
    targetEntityId: 'tables',
    label: '1 : N',
  },
  {
    relationId: 'public7',
    sourceEntityId: 'users',
    targetEntityId: 'players',
    label: '1 : N',
  },
  {
    relationId: 'public8',
    sourceEntityId: 'tables',
    targetEntityId: 'players',
    label: '1 : N',
  },
  {
    relationId: 'public9',
    sourceEntityId: 'users',
    targetEntityId: 'players_active',
    label: '1 : N',
  },
  {
    relationId: 'public10',
    sourceEntityId: 'players',
    targetEntityId: 'players_active',
    label: '1 : N',
  },
  {
    relationId: 'public11',
    sourceEntityId: 'tables',
    targetEntityId: 'hands',
    label: '1 : N',
  },
  {
    relationId: 'public12',
    sourceEntityId: 'players',
    targetEntityId: 'hands',
    label: '1 : N',
  },
  {
    relationId: 'public13',
    sourceEntityId: 'players',
    targetEntityId: 'hands',
    label: '1 : N',
  },
  {
    relationId: 'public14',
    sourceEntityId: 'tables',
    targetEntityId: 'hands_active',
    label: '1 : N',
  },
  {
    relationId: 'public15',
    sourceEntityId: 'hands',
    targetEntityId: 'hands_active',
    label: '1 : N',
  },
  {
    relationId: 'public16',
    sourceEntityId: 'hands',
    targetEntityId: 'pots',
    label: '1 : N',
  },
  {
    relationId: 'public17',
    sourceEntityId: 'hands',
    targetEntityId: 'betting_rounds',
    label: '1 : N',
  },
  {
    relationId: 'public18',
    sourceEntityId: 'players',
    targetEntityId: 'betting_rounds',
    label: '1 : N',
  },
  {
    relationId: 'public19',
    sourceEntityId: 'betting_rounds',
    targetEntityId: 'betting_rounds_active',
    label: '1 : N',
  },
  {
    relationId: 'public20',
    sourceEntityId: 'hands',
    targetEntityId: 'betting_rounds_active',
    label: '1 : N',
  },
  {
    relationId: 'public21',
    sourceEntityId: 'players',
    targetEntityId: 'bets',
    label: '1 : N',
  },
  {
    relationId: 'public22',
    sourceEntityId: 'betting_rounds',
    targetEntityId: 'bets',
    label: '1 : N',
  },
  {
    relationId: 'public23',
    sourceEntityId: 'players',
    targetEntityId: 'holdings',
    label: '1 : N',
  },
  {
    relationId: 'public24',
    sourceEntityId: 'hands',
    targetEntityId: 'holdings',
    label: '1 : N',
  },
  {
    relationId: 'public25',
    sourceEntityId: 'holdings',
    targetEntityId: 'holdings_to_cards',
    label: '1 : N',
  },
  {
    relationId: 'public26',
    sourceEntityId: 'cards',
    targetEntityId: 'holdings_to_cards',
    label: '1 : N',
  },
  {
    relationId: 'public27',
    sourceEntityId: 'holdings',
    targetEntityId: 'actions',
    label: '1 : N',
  },
];
